---


- name: "{{ beats_flavor }}: Ensure configuration directory exists"
  file:
    path: "{{ beats_path_config }}"
    state: directory
    mode: '0777'
    recurse: true
  changed_when: false

- name: "{{ beats_flavor }}: Create configuration file"
  template:
    dest: >-
      {%- if item == 'beats.yml' -%}
      {{ beats_path_config }}/{{ beats_flavor }}.yml
      {%- else -%}
      {{ beats_path_config }}/{{ item | basename }}
      {%- endif -%}
    mode: '0644'
    src: "{{ item }}"
  with_items:
    - beats.yml
    - fields.yml
  changed_when: false



#-------- Unsure if this is needed ---------#

#- name: set vm.max_map_count to 262144 in sysctl
 # sysctl:
  #  name: "{{ item.key }}"
   # value: "{{ item.value }}"
  #with_items:
   # - {key: "vm.max_map_count", value: "262144"}
