---


- name: copy beats script
  template:
    src: "{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: 0755
    owner: root
    group: root
  with_items:
    - Dockerfile
    - beats
  notify: beats-restart-service
