---

- name: "{{ beats_flavor }}: Create inputs directory"
  block:
    - name: "{{ beats_flavor }}: Create inputs directory on Linux"
      file:
        path: "{{ beats_filebeat_inputs_dir }}"
        mode: 0o755
        state: directory
      when: ansible_os_family != 'Windows'

    - name: "{{ beats_flavor }}: Create inputs directory on Windows"
      win_file:
        path: "{{ beats_filebeat_inputs_dir }}"
        state: directory
      when: ansible_os_family == 'Windows'


- name: "{{ beats_flavor }}: Upload inputs"
  block:
    - name: "{{ beats_flavor }}: Upload inputs on Linux"
      template:
        src: "{{ _beats__input_file }}"
        dest: >-
          {{ beats_filebeat_inputs_dir }}/{{
            _beats__input_file | basename | regex_replace('^(.*)[.]j2', '\\1')
          }}
        mode: 0o600
      loop: "{{ beats_filebeat_input_files }}"
      loop_control:
        loop_var: _beats__input_file
      when: ansible_os_family != 'Windows'
      notify: beats-restart-service

    - name: "{{ beats_flavor }}: Upload inputs on Windows"
      win_template:
        src: "{{ _beats__input_file }}"
        dest: >-
          {{ beats_filebeat_input_files }}/{{
            _beats__input_file | basename | regex_replace('^(.*)[.]j2', '\\1')
          }}
      loop: "{{ beats_filebeat_input_files }}"
      loop_control:
        loop_var: _beats__input_file
      when: ansible_os_family == 'Windows'
      notify: beats-restart-service


- name: "{{ beats_flavor }}: Create modules directory"
  block:
    - name: "{{ beats_flavor }}: Create modules directory on Linux"
      file:
        path: "{{ beats_filebeat_modules_dir }}"
        mode: 0o644
        state: directory
      when: ansible_os_family != 'Windows'
    - name: "{{ beats_flavor }}: Create modules directory on Windows"
      win_file:
        path: "{{ beats_filebeat_modules_dir }}"
        state: directory
      when: ansible_os_family == 'Windows'


- name: "{{ beats_flavor }}: Upload modules"
  block:
    - name: "{{ beats_flavor }}: Upload modules on Linux"
      template:
        src: "{{ _beats__module }}"
        dest: >-
          {{ beats_filebeat_modules_dir }}/{{
            _beats__module | basename | regex_replace('^(.*)[.]j2', '\\1')
          }}
        mode: 0o644
      loop: "{{ beats_filebeat_module_files }}"
      loop_control:
        loop_var: _beats__module
      when: ansible_os_family != 'Windows'
      notify: beats-restart-service

    - name: "{{ beats_flavor }}: Upload modules on Windows"
      win_template:
        src: "{{ _beats__module }}"
        dest: >-
          {{ beats_filebeat_modules_dir }}/{{
            _beats__module | basename | regex_replace('^(.*)[.]j2', '\\1')
          }}
      loop: "{{ beats_filebeat_module_files }}"
      loop_control:
        loop_var: _beats__module
      when: ansible_os_family == 'Windows'
      notify: beats-restart-service

- name: "{{ beats_flavor }}: Enable filebeat modules on Linux"
  block:
    - name: "{{ beats_flavor }}: Check if filebeat modules are enabled on Linux"
      stat:
        path: "{{ beats_filebeat_modules_dir }}/{{ _beats__module }}.yml"
      register: _beats_filebeat_enabled_modules
      loop: "{{ beats_filebeat_modules }}"
      loop_control:
        loop_var: _beats__module

    - name: "{{ beats_flavor }}: Enable filebeat modules on Linux"
      command: "docker exec {{ beats_flavor }} {{ beats_flavor }} \
          --path.data /usr/share/{{ beats_flavor }}/data \
          --path.config /usr/share/{{ beats_flavor }} \
          --path.home {{ beats_path_home }} \
          --path.logs modules enable {{ modules_to_enable }}"
      when: modules_to_enable | length > 0
      vars:
        modules_to_enable: >-
          {{
            beats_filebeat_modules
            | reject('in', _beats_filebeat_enabled_modules.results
                           | selectattr('stat.exists')
                           | map(attribute='stat.path')
                           | map('basename')
                           | map('replace', '.yml', '')
            )
            | join(' ')
            | default('', true)
          }}
  when: ansible_os_family != 'Windows'

- name: "{{ beats_flavor }}: Enable filebeat modules on Windows"
  block:
    - name: "{{ beats_flavor }}: Check if filebeat modules are enabled on Windows"
      win_stat:
        path: "{{ beats_filebeat_modules_dir }}/{{ _beats__module }}.yml"
      register: _beats_filebeat_enabled_modules
      loop: "{{ beats_filebeat_modules }}"
      loop_control:
        loop_var: _beats__module

    - name: "{{ beats_flavor }}: Enable filebeat modules on Windows"
      win_command: "{{ beats_win_exec }} modules enable {{ modules_to_enable }}"
      when: modules_to_enable | length > 0
      vars:
        modules_to_enable: >-
          {{
            beats_filebeat_modules
            | reject('in', _beats_filebeat_enabled_modules.results
                           | selectattr('stat.exists')
                           | map(attribute='stat.path')
                           | map('basename')
                           | map('replace', '.yml', '')
            )
            | join(' ')
            | default('', true)
          }}
  when: ansible_os_family == 'Windows'

- name: "{{ beats_flavor }}: Disable filebeat modules on Linux"
  block:
    - name: "{{ beats_flavor }}: Check if filebeat modules are disabled on Linux"
      stat:
        path: "{{ beats_filebeat_modules_dir }}/{{ _beats__module }}.yml"
      register: _beats_filebeat_disabled_modules
      loop: "{{ beats_filebeat_modules }}"
      loop_control:
        loop_var: _beats__module

    - name: "{{ beats_flavor }}: Disable filebeat modules on Linux"
      command: "docker exec {{ beats_flavor }} {{ beats_flavor }} \
          --path.data /usr/share/{{ beats_flavor }}/data \
          --path.config /usr/share/{{ beats_flavor }} \
          --path.home {{ beats_path_home }} \
          --path.logs modules disable {{ modules_to_disable }}"
      when: modules_to_disable | length > 0
      vars:
        modules_to_disable: >-
          {{
            beats_filebeat_modules_disable
            | reject('in', _beats_filebeat_disabled_modules.results
                           | selectattr('stat.exists')
                           | map(attribute='stat.path')
                           | map('basename')
                           | map('replace', '.yml', '')
            )
            | join(' ')
            | default('', true)
          }}
  when: ansible_os_family != 'Windows'

- name: "{{ beats_flavor }}: Disable filebeat modules on Windows"
  block:
    - name: "{{ beats_flavor }}: Check if filebeat modules are disabled on Windows"
      win_stat:
        path: "{{ beats_filebeat_modules_dir }}/{{ _beats__module }}.yml"
      register: _beats_filebeat_disabled_modules
      loop: "{{ beats_filebeat_modules }}"
      loop_control:
        loop_var: _beats__module

    - name: "{{ beats_flavor }}: Disable filebeat modules on Windows"
      win_command: "{{ beats_win_exec }} modules disable {{ modules_to_disable }}"
      when: modules_to_disable | length > 0
      vars:
        modules_to_disable: >-
          {{
            beats_filebeat_modules_disable
            | reject('in', _beats_filebeat_disabled_modules.results
                           | selectattr('stat.exists')
                           | map(attribute='stat.path')
                           | map('basename')
                           | map('replace', '.yml', '')
            )
            | join(' ')
            | default('', true)
          }}

  when: ansible_os_family == 'Windows'
